// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCtRjMQOKp1JfLSzt8WU9Jlkcs7QzRuLM',
    appId: '1:172553043874:web:28ecefcec41147de9d7cfb',
    messagingSenderId: '172553043874',
    projectId: 'halal-scanner-ai-67e91',
    authDomain: 'halal-scanner-ai-67e91.firebaseapp.com',
    storageBucket: 'halal-scanner-ai-67e91.firebasestorage.app',
    measurementId: 'G-6KD3ZQ2E00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKAO5-cJHJ8Q84nHAp1q0fYnGfITf-gmI',
    appId: '1:172553043874:android:4c516a4686a1e8be9d7cfb',
    messagingSenderId: '172553043874',
    projectId: 'halal-scanner-ai-67e91',
    storageBucket: 'halal-scanner-ai-67e91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRTmEMLrH-y8CNzY-wnXCcE55o35ZAvE',
    appId: '1:172553043874:ios:bdcb33cefae4557a9d7cfb',
    messagingSenderId: '172553043874',
    projectId: 'halal-scanner-ai-67e91',
    storageBucket: 'halal-scanner-ai-67e91.firebasestorage.app',
    iosBundleId: 'com.clearbite.clearbite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvRTmEMLrH-y8CNzY-wnXCcE55o35ZAvE',
    appId: '1:172553043874:ios:bdcb33cefae4557a9d7cfb',
    messagingSenderId: '172553043874',
    projectId: 'halal-scanner-ai-67e91',
    storageBucket: 'halal-scanner-ai-67e91.firebasestorage.app',
    iosBundleId: 'com.clearbite.clearbite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCtRjMQOKp1JfLSzt8WU9Jlkcs7QzRuLM',
    appId: '1:172553043874:web:af8415c89f4b50829d7cfb',
    messagingSenderId: '172553043874',
    projectId: 'halal-scanner-ai-67e91',
    authDomain: 'halal-scanner-ai-67e91.firebaseapp.com',
    storageBucket: 'halal-scanner-ai-67e91.firebasestorage.app',
    measurementId: 'G-ZMBMXGJ5YT',
  );
}
